const store = {
  state: {
    commonCodes: [
      {
        commonGroupCode: 'JOFR_JHNT_CD',
        commonCode: 'JOFR',
        commonCodeName: '구인',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'JOFR_JHNT_CD',
        commonCode: 'JHNT',
        commonCodeName: '구직',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'QLF_CD',
        commonCode: 'QLF_CD_001',
        commonCodeName: '치과위생사',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'QLF_CD',
        commonCode: 'QLF_CD_002',
        commonCodeName: '간호조무사',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'QLF_CD',
        commonCode: 'QLF_CD_003',
        commonCodeName: '치과기공사',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'QLF_CD',
        commonCode: 'QLF_CD_004',
        commonCodeName: '치과의사',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'QLF_CD',
        commonCode: 'QLF_CD_005',
        commonCodeName: '코디네이터',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'QLF_CD',
        commonCode: 'QLF_CD_999',
        commonCodeName: '기타',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'BIZ_CD',
        commonCode: 'BIZ_CD_ALL',
        commonCodeName: '무관',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'BIZ_CD',
        commonCode: 'BIZ_CD_001',
        commonCodeName: '진료실',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'BIZ_CD',
        commonCode: 'BIZ_CD_002',
        commonCodeName: '데스크',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'BIZ_CD',
        commonCode: 'BIZ_CD_003',
        commonCodeName: '상담/코디',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'BIZ_CD',
        commonCode: 'BIZ_CD_004',
        commonCodeName: '보험청구',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'BIZ_CD',
        commonCode: 'BIZ_CD_005',
        commonCodeName: '경영지원/관리',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'BIZ_CD',
        commonCode: 'BIZ_CD_999',
        commonCodeName: '기타',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MAJR_CD',
        commonCode: 'MAJR_CD_ALL',
        commonCodeName: '무관',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MAJR_CD',
        commonCode: 'MAJR_CD_001',
        commonCodeName: '구강악안면외과',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MAJR_CD',
        commonCode: 'MAJR_CD_002',
        commonCodeName: '치과교정과',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MAJR_CD',
        commonCode: 'MAJR_CD_003',
        commonCodeName: '치과보철과',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MAJR_CD',
        commonCode: 'MAJR_CD_004',
        commonCodeName: '치주과',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MAJR_CD',
        commonCode: 'MAJR_CD_005',
        commonCodeName: '치과보존과',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MAJR_CD',
        commonCode: 'MAJR_CD_006',
        commonCodeName: '예방치과',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MAJR_CD',
        commonCode: 'MAJR_CD_007',
        commonCodeName: '구강내과',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MAJR_CD',
        commonCode: 'MAJR_CD_008',
        commonCodeName: '소아치과',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MAJR_CD',
        commonCode: 'MAJR_CD_009',
        commonCodeName: '통합치의학과',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MAJR_CD',
        commonCode: 'MAJR_CD_010',
        commonCodeName: '구강병리과',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MAJR_CD',
        commonCode: 'MAJR_CD_011',
        commonCodeName: '영상치의학과',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'CARR_CD',
        commonCode: 'CARR_CD_ALL',
        commonCodeName: '무관',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'CARR_CD',
        commonCode: 'CARR_CD_001',
        commonCodeName: '1년미만',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'CARR_CD',
        commonCode: 'CARR_CD_002',
        commonCodeName: '1~3년',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'CARR_CD',
        commonCode: 'CARR_CD_003',
        commonCodeName: '4~6년',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'CARR_CD',
        commonCode: 'CARR_CD_004',
        commonCodeName: '7~9년',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'CARR_CD',
        commonCode: 'CARR_CD_005',
        commonCodeName: '10년이상',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'EMPL_SHAPE_CD',
        commonCode: 'EMPL_SHAPE_CD_ALL',
        commonCodeName: '무관',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'EMPL_SHAPE_CD',
        commonCode: 'EMPL_SHAPE_CD_001',
        commonCodeName: '정규직',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'EMPL_SHAPE_CD',
        commonCode: 'EMPL_SHAPE_CD_002',
        commonCodeName: '계약직',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'EMPL_SHAPE_CD',
        commonCode: 'EMPL_SHAPE_CD_004',
        commonCodeName: '파트타임',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'WORK_SHAPE_CD',
        commonCode: 'WORK_SHAPE_CD_ALL',
        commonCodeName: '무관',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'WORK_SHAPE_CD',
        commonCode: 'WORK_SHAPE_CD_001',
        commonCodeName: '월~금',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'WORK_SHAPE_CD',
        commonCode: 'WORK_SHAPE_CD_002',
        commonCodeName: '월~토(토요일 격주휴무)',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'WORK_SHAPE_CD',
        commonCode: 'WORK_SHAPE_CD_003',
        commonCodeName: '월~토',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'WORK_SHAPE_CD',
        commonCode: 'WORK_SHAPE_CD_004',
        commonCodeName: '주37.5시간',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'WORK_SHAPE_CD',
        commonCode: 'WORK_SHAPE_CD_005',
        commonCodeName: '주40시간',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'WORK_SHAPE_CD',
        commonCode: 'WORK_SHAPE_CD_006',
        commonCodeName: '주52시간',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'WORK_SHAPE_CD',
        commonCode: 'WORK_SHAPE_CD_007',
        commonCodeName: '야간근무',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'WORK_SHAPE_CD',
        commonCode: 'WORK_SHAPE_CD_008',
        commonCodeName: '야간당직',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'WORK_SHAPE_CD',
        commonCode: 'WORK_SHAPE_CD_009',
        commonCodeName: '주말당직',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'WLFR_CD',
        commonCode: 'WLFR_CD_ALL',
        commonCodeName: '무관',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'WLFR_CD',
        commonCode: 'WLFR_CD_001',
        commonCodeName: '숙소',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'WLFR_CD',
        commonCode: 'WLFR_CD_002',
        commonCodeName: '식사',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'WLFR_CD',
        commonCode: 'WLFR_CD_003',
        commonCodeName: '교육비',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'WLFR_CD',
        commonCode: 'WLFR_CD_005',
        commonCodeName: '청소/소독직원 상주',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'WLFR_CD',
        commonCode: 'WLFR_CD_006',
        commonCodeName: '4대보험',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'WLFR_CD',
        commonCode: 'WLFR_CD_007',
        commonCodeName: '퇴직금',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'WLFR_CD',
        commonCode: 'WLFR_CD_008',
        commonCodeName: '인센티브',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'WLFR_CD',
        commonCode: 'WLFR_CD_009',
        commonCodeName: '초과근무수당',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'RSME_WRT_CD',
        commonCode: 'RSME_WRT_CD_000',
        commonCodeName: '임시저장',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'RSME_WRT_CD',
        commonCode: 'RSME_WRT_CD_100',
        commonCodeName: '저장',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SCH_DVCD',
        commonCode: 'SCH_DVCD_001',
        commonCodeName: '고등학교',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SCH_DVCD',
        commonCode: 'SCH_DVCD_002',
        commonCodeName: '대학교(2,3년)',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SCH_DVCD',
        commonCode: 'SCH_DVCD_003',
        commonCodeName: '대학교',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SCH_DVCD',
        commonCode: 'SCH_DVCD_004',
        commonCodeName: '대학원',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SCH_DVCD',
        commonCode: 'SCH_DVCD_005',
        commonCodeName: '추가학교',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'GRDT_STACD',
        commonCode: 'GRDT_STACD_001',
        commonCodeName: '졸업',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'GRDT_STACD',
        commonCode: 'GRDT_STACD_002',
        commonCodeName: '졸업예정',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'GRDT_STACD',
        commonCode: 'GRDT_STACD_003',
        commonCodeName: '수료',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'GRDT_STACD',
        commonCode: 'GRDT_STACD_004',
        commonCodeName: '중퇴(자퇴)',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'GRDT_STACD',
        commonCode: 'GRDT_STACD_005',
        commonCodeName: '재학',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'GRDT_STACD',
        commonCode: 'GRDT_STACD_006',
        commonCodeName: '휴학',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'GRDT_STACD',
        commonCode: 'GRDT_STACD_007',
        commonCodeName: '검정고시',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'CRF_DVCD',
        commonCode: 'CRF_DVCD_001',
        commonCodeName: '치과위생사',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'CRF_DVCD',
        commonCode: 'CRF_DVCD_002',
        commonCodeName: '코디네이터',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'CRF_DVCD',
        commonCode: 'CRF_DVCD_003',
        commonCodeName: '치과의사',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'CRF_DVCD',
        commonCode: 'CRF_DVCD_004',
        commonCodeName: '마취사',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'CRF_DVCD',
        commonCode: 'CRF_DVCD_005',
        commonCodeName: '보험청구사',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'CRF_DVCD',
        commonCode: 'CRF_DVCD_006',
        commonCodeName: '외국어',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'CRF_DVCD',
        commonCode: 'CRF_DVCD_007',
        commonCodeName: '운전면허',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'CRF_DVCD',
        commonCode: 'CRF_DVCD_008',
        commonCodeName: '간호조무사',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'CRF_DVCD',
        commonCode: 'CRF_DVCD_009',
        commonCodeName: '치과기공사',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'CRF_DVCD',
        commonCode: 'CRF_DVCD_999',
        commonCodeName: '기타',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'HIRE_ANUN_STACD',
        commonCode: 'HIRE_ANUN_STACD_000',
        commonCodeName: '임시저장',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'HIRE_ANUN_STACD',
        commonCode: 'HIRE_ANUN_STACD_100',
        commonCodeName: '진행중',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'HIRE_ANUN_STACD',
        commonCode: 'HIRE_ANUN_STACD_800',
        commonCodeName: '강제종료',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'HIRE_ANUN_STACD',
        commonCode: 'HIRE_ANUN_STACD_801',
        commonCodeName: '기간만료',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'HIRE_ANUN_STACD',
        commonCode: 'HIRE_ANUN_STACD_900',
        commonCodeName: '채용완료',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'END_RSN_CD',
        commonCode: 'END_RSN_CD_001',
        commonCodeName: '채용완료',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'END_RSN_CD',
        commonCode: 'END_RSN_CD_002',
        commonCodeName: '채용포기',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'END_RSN_CD',
        commonCode: 'END_RSN_CD_003',
        commonCodeName: '신규공고',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'END_RSN_CD',
        commonCode: 'END_RSN_CD_004',
        commonCodeName: '재공고',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'HIRE_PATH_CD',
        commonCode: 'HIRE_PATH_CD_001',
        commonCodeName: '덴잡',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'HIRE_PATH_CD',
        commonCode: 'HIRE_PATH_CD_002',
        commonCodeName: '덴탈잡',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'HIRE_PATH_CD',
        commonCode: 'HIRE_PATH_CD_003',
        commonCodeName: '사람인',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'HIRE_PATH_CD',
        commonCode: 'HIRE_PATH_CD_004',
        commonCodeName: '잡코리아',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'HIRE_PATH_CD',
        commonCode: 'HIRE_PATH_CD_005',
        commonCodeName: '벼룩시장',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'HIRE_PATH_CD',
        commonCode: 'HIRE_PATH_CD_999',
        commonCodeName: '기타',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'ENTR_RQST_STACD',
        commonCode: 'ENTR_RQST_STACD_700',
        commonCodeName: '입사요청 취소',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'ENTR_RQST_STACD',
        commonCode: 'ENTR_RQST_STACD_900',
        commonCodeName: '입사요청 완료',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'INTRV_SGST_STACD',
        commonCode: 'INTRV_SGST_STACD_100',
        commonCodeName: '면접 제의중',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'INTRV_SGST_STACD',
        commonCode: 'INTRV_SGST_STACD_200',
        commonCodeName: '면접일시 조율중',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'INTRV_SGST_STACD',
        commonCode: 'INTRV_SGST_STACD_201',
        commonCodeName: '면접일시 조율중',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'INTRV_SGST_STACD',
        commonCode: 'INTRV_SGST_STACD_210',
        commonCodeName: '면접일시 확정',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'INTRV_SGST_STACD',
        commonCode: 'INTRV_SGST_STACD_211',
        commonCodeName: '면접일시 확정',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'INTRV_SGST_STACD',
        commonCode: 'INTRV_SGST_STACD_700',
        commonCodeName: '면접 취소',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'INTRV_SGST_STACD',
        commonCode: 'INTRV_SGST_STACD_701',
        commonCodeName: '면접 취소',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'INTRV_SGST_STACD',
        commonCode: 'INTRV_SGST_STACD_900',
        commonCodeName: '면접 종료',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'PASS_NOTI_STACD',
        commonCode: 'PASS_NOTI_STACD_000',
        commonCodeName: '예비합격',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'PASS_NOTI_STACD',
        commonCode: 'PASS_NOTI_STACD_100',
        commonCodeName: '입사 제의중',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'PASS_NOTI_STACD',
        commonCode: 'PASS_NOTI_STACD_200',
        commonCodeName: '입사일시 조율중',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'PASS_NOTI_STACD',
        commonCode: 'PASS_NOTI_STACD_201',
        commonCodeName: '입사일시 조율중',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'PASS_NOTI_STACD',
        commonCode: 'PASS_NOTI_STACD_210',
        commonCodeName: '입사일시 확정',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'PASS_NOTI_STACD',
        commonCode: 'PASS_NOTI_STACD_211',
        commonCodeName: '입사일시 확정',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'PASS_NOTI_STACD',
        commonCode: 'PASS_NOTI_STACD_700',
        commonCodeName: '입사 취소',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'PASS_NOTI_STACD',
        commonCode: 'PASS_NOTI_STACD_701',
        commonCodeName: '입사 취소',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'PASS_NOTI_STACD',
        commonCode: 'PASS_NOTI_STACD_900',
        commonCodeName: '입사 종료',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'PASS_NOTI_STACD',
        commonCode: 'PASS_NOTI_STACD_901',
        commonCodeName: '입사 포기',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_000',
        commonCodeName: '일반대화',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_110',
        commonCodeName: '구직자_채용공고_열람',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_111',
        commonCodeName: '구직자_채용공고_열람_정보전달',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_120',
        commonCodeName: '구직자_입사요청_전달',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_121',
        commonCodeName: '구직자_입사요청_수정',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_122',
        commonCodeName: '구직자_입사요청_취소',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_130',
        commonCodeName: '구직자_면접제의_열람',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_131',
        commonCodeName: '구직자_면접제의_면접일시_변경',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_132',
        commonCodeName: '구직자_면접제의_면접일시_확정',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_133',
        commonCodeName: '구직자_면접제의_취소',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_140',
        commonCodeName: '구직자_합격통지_열람',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_141',
        commonCodeName: '구직자_합격통지_입사일시_변경',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_142',
        commonCodeName: '구직자_합격통지_입사일시_확정',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_143',
        commonCodeName: '구직자_합격통지_취소',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_210',
        commonCodeName: '구인자_이력서_열람',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_211',
        commonCodeName: '구인자_이력서_열람_정보전달',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_220',
        commonCodeName: '구인자_입사요청_열람',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_230',
        commonCodeName: '구인자_면접제의_전달',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_231',
        commonCodeName: '구인자_면접제의_수정',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_232',
        commonCodeName: '구인자_면접제의_면접일시_변경',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_233',
        commonCodeName: '구인자_면접제의_면접일시_확정',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_234',
        commonCodeName: '구인자_면접제의_취소',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_240',
        commonCodeName: '구인자_합격통지_전달',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_241',
        commonCodeName: '구인자_합격통지_수정',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_242',
        commonCodeName: '구인자_합격통지_입사일시_변경요청',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_243',
        commonCodeName: '구인자_합격통지_입사일시_수락',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MSG_CN_TYCD',
        commonCode: 'MSG_CN_TYCD_244',
        commonCodeName: '구인자_합격통지_취소',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SIDO_CD',
        commonCode: '11',
        commonCodeName: '서울',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SIDO_CD',
        commonCode: '26',
        commonCodeName: '부산',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SIDO_CD',
        commonCode: '27',
        commonCodeName: '대구',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SIDO_CD',
        commonCode: '28',
        commonCodeName: '인천',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SIDO_CD',
        commonCode: '29',
        commonCodeName: '광주',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SIDO_CD',
        commonCode: '30',
        commonCodeName: '대전',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SIDO_CD',
        commonCode: '31',
        commonCodeName: '울산',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SIDO_CD',
        commonCode: '36',
        commonCodeName: '세종',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SIDO_CD',
        commonCode: '41',
        commonCodeName: '경기',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SIDO_CD',
        commonCode: '51',
        commonCodeName: '강원',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SIDO_CD',
        commonCode: '43',
        commonCodeName: '충북',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SIDO_CD',
        commonCode: '44',
        commonCodeName: '충남',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SIDO_CD',
        commonCode: '52',
        commonCodeName: '전북',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SIDO_CD',
        commonCode: '46',
        commonCodeName: '전남',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SIDO_CD',
        commonCode: '47',
        commonCodeName: '경북',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SIDO_CD',
        commonCode: '48',
        commonCodeName: '경남',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SIDO_CD',
        commonCode: '50',
        commonCodeName: '제주',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_REGN_CD',
        commonCode: 'SBWY_REGN_CD_001',
        commonCodeName: '수도권',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_REGN_CD',
        commonCode: 'SBWY_REGN_CD_002',
        commonCodeName: '부산',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_REGN_CD',
        commonCode: 'SBWY_REGN_CD_003',
        commonCodeName: '대구',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_REGN_CD',
        commonCode: 'SBWY_REGN_CD_004',
        commonCodeName: '광주',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_REGN_CD',
        commonCode: 'SBWY_REGN_CD_005',
        commonCodeName: '대전',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_001',
        commonCodeName: '수도권 1호선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_002',
        commonCodeName: '수도권 2호선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_003',
        commonCodeName: '수도권 3호선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_004',
        commonCodeName: '수도권 4호선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_005',
        commonCodeName: '수도권 5호선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_006',
        commonCodeName: '수도권 6호선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_007',
        commonCodeName: '수도권 7호선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_008',
        commonCodeName: '수도권 8호선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_009',
        commonCodeName: '수도권 9호선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_010',
        commonCodeName: '서해선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_011',
        commonCodeName: '수인분당선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_012',
        commonCodeName: '신분당선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_013',
        commonCodeName: '인천 1호선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_014',
        commonCodeName: '인천 2호선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_015',
        commonCodeName: '경의중앙선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_016',
        commonCodeName: '경춘선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_017',
        commonCodeName: '공항철도',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_018',
        commonCodeName: '의정부경전철',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_019',
        commonCodeName: '에버라인',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_020',
        commonCodeName: '경강선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_021',
        commonCodeName: '우이신설선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_022',
        commonCodeName: '김포골드라인',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_023',
        commonCodeName: '신림선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_024',
        commonCodeName: '자기부상철도',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_025',
        commonCodeName: '부산 1호선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_026',
        commonCodeName: '부산 2호선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_027',
        commonCodeName: '부산 3호선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_028',
        commonCodeName: '부산 4호선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_029',
        commonCodeName: '부산김해경전철',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_030',
        commonCodeName: '동해선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_031',
        commonCodeName: '대구 1호선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_032',
        commonCodeName: '대구 2호선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_033',
        commonCodeName: '대구 3호선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_034',
        commonCodeName: '광주 1호선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SBWY_LINE_CD',
        commonCode: 'SBWY_LINE_CD_035',
        commonCodeName: '대전 1호선',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MTRT_SBJ_CD',
        commonCode: '50',
        commonCodeName: '구강악안면외과',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MTRT_SBJ_CD',
        commonCode: '51',
        commonCodeName: '치과보철과',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MTRT_SBJ_CD',
        commonCode: '52',
        commonCodeName: '치과교정과',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MTRT_SBJ_CD',
        commonCode: '53',
        commonCodeName: '소아치과',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MTRT_SBJ_CD',
        commonCode: '54',
        commonCodeName: '치주과',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MTRT_SBJ_CD',
        commonCode: '55',
        commonCodeName: '치과보존과',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MTRT_SBJ_CD',
        commonCode: '56',
        commonCodeName: '구강내과',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MTRT_SBJ_CD',
        commonCode: '57',
        commonCodeName: '영상치의학과',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MTRT_SBJ_CD',
        commonCode: '58',
        commonCodeName: '구강병리과',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MTRT_SBJ_CD',
        commonCode: '59',
        commonCodeName: '예방치과',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SEX_DVCD',
        commonCode: 'M',
        commonCodeName: '남성',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'SEX_DVCD',
        commonCode: 'F',
        commonCodeName: '여성',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MEM_STAT_CD',
        commonCode: 'W',
        commonCodeName: '대기',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MEM_STAT_CD',
        commonCode: 'N',
        commonCodeName: '정상',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MEM_STAT_CD',
        commonCode: 'D',
        commonCodeName: '휴면',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MEM_STAT_CD',
        commonCode: 'X',
        commonCodeName: '정지',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'TRMS_TYCD',
        commonCode: 'USE_TRMS',
        commonCodeName: '사이트 이용',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'TRMS_TYCD',
        commonCode: 'PRV_TRMS',
        commonCodeName: '개인정보 처리방침',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'TRMS_TYCD',
        commonCode: 'MKT_TRMS',
        commonCodeName: '마케팅 수신 동의',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'TRMS_TYCD',
        commonCode: 'PRA_TRMS',
        commonCodeName: '개인정보 수집·이용 동의',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'TRMS_TYCD',
        commonCode: 'PRC_TRMS',
        commonCodeName: '개인정보 수집·이용 동의 (선택)',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MEM_JBCS_CD',
        commonCode: 'DEN_DOC',
        commonCodeName: '치과의사',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MEM_JBCS_CD',
        commonCode: 'DEN_TCH',
        commonCodeName: '치과기공사',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MEM_JBCS_CD',
        commonCode: 'DEN_HYG',
        commonCodeName: '치과위생사',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MEM_JBCS_CD',
        commonCode: 'DEN_NRS',
        commonCodeName: '치과간호사',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MEM_JBCS_CD',
        commonCode: 'DEN_NRA',
        commonCodeName: '치과간호조무사',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MEM_JBCS_CD',
        commonCode: 'DEN_CRD',
        commonCodeName: '치과코디네이터',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MEM_JBCS_CD',
        commonCode: 'DEN_OFW',
        commonCodeName: '치과사무직',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MEM_JBCS_CD',
        commonCode: 'DEN_STD',
        commonCodeName: '치과계학생',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MEM_JBCS_CD',
        commonCode: 'DEN_ETC',
        commonCodeName: '치과계기타',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MEM_JBCS_CD',
        commonCode: 'MED_DOC',
        commonCodeName: '의사',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MEM_JBCS_CD',
        commonCode: 'MED_NRS',
        commonCodeName: '간호사',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MEM_JBCS_CD',
        commonCode: 'MED_NRA',
        commonCodeName: '간호조무사',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MEM_JBCS_CD',
        commonCode: 'MED_CRD',
        commonCodeName: '병원코디네이터',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MEM_JBCS_CD',
        commonCode: 'MED_OFW',
        commonCodeName: '병원사무직',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MEM_JBCS_CD',
        commonCode: 'MED_STD',
        commonCodeName: '의료계학생',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MEM_JBCS_CD',
        commonCode: 'MED_ETC',
        commonCodeName: '의료계기타',
        useYn: 'Y',
      },
      {
        commonGroupCode: 'MEM_JBCS_CD',
        commonCode: 'ETC',
        commonCodeName: '기타',
        useYn: 'Y',
      },
    ],
  },
  setState(newState) {
    this.state = { ...this.state, ...newState };
  },
};

module.exports = store;
