const store = {
  state: {
    jobList: [
      {
        customerName: '의료법인사과나무의료재단',
        businessmanCustomerCode: '71033',
        hireAnnounceSequenceNumber: 4,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName:
          '★ 일산 사과나무치과병원 치과위생사 모집(경력 무관) ★',
        recruitStartDate: '2024-03-15',
        recruitEndDate: '2026-03-15',
        qualification: 'QLF_CD_001',
        sidoCode: '41',
        sigunguCode: '287',
        fileId: '518f9062-7a66-4d68-868e-132b3d4bd0eb',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'Y',
      },
      {
        customerName: '서울치과',
        businessmanCustomerCode: '33721',
        hireAnnounceSequenceNumber: 59180,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName:
          '교정전문병원 채용 계약시 계약 보너스(150)만원 지급합니다 ',
        recruitStartDate: '2024-03-20',
        recruitEndDate: '2024-04-30',
        qualification: 'QLF_CD_001|QLF_CD_002',
        sidoCode: '11',
        sigunguCode: '710',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'Y',
        decimalDay: 39,
        topYesOrNo: 'N',
      },
      {
        customerName: '현치과의원',
        businessmanCustomerCode: '6996',
        hireAnnounceSequenceNumber: 2,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '현치과에서 함께할 가족을 원합니다. ',
        recruitStartDate: '2024-03-18',
        recruitEndDate: '2024-03-29',
        qualification: 'QLF_CD_001',
        sidoCode: '44',
        sigunguCode: '200',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        decimalDay: 7,
        topYesOrNo: 'N',
      },
      {
        customerName: '다인치과(부평)',
        businessmanCustomerCode: '7651',
        hireAnnounceSequenceNumber: 66308,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '진료실 선생님 모십니다.',
        recruitStartDate: '2024-03-13',
        recruitEndDate: '2024-04-13',
        qualification: 'QLF_CD_001|QLF_CD_002',
        sidoCode: '28',
        sigunguCode: '237',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        decimalDay: 22,
        topYesOrNo: 'N',
      },
      {
        customerName: '삼성바이오치과',
        businessmanCustomerCode: '877068',
        hireAnnounceSequenceNumber: 1,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '삼성바이오치과 치위생사 구입합니다',
        recruitStartDate: '2024-03-11',
        recruitEndDate: '2024-03-22',
        qualification: 'QLF_CD_001',
        sidoCode: '28',
        sigunguCode: '185',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        decimalDay: 0,
        topYesOrNo: 'N',
      },
      {
        customerName: '의료법인효산의료재단',
        businessmanCustomerCode: '9531',
        hireAnnounceSequenceNumber: 2,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '치과 원장님 2분 정중히 모십니다.',
        recruitStartDate: '2024-03-08',
        recruitEndDate: '2024-05-31',
        qualification: 'QLF_CD_004',
        fileId: '1ae5f19b-bcad-49ee-ac63-c6a4a442086d',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        decimalDay: 70,
        topYesOrNo: 'N',
      },
      {
        customerName: '세란치과의원',
        businessmanCustomerCode: '5361',
        hireAnnounceSequenceNumber: 67935,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName:
          '남성역 세란치과에서 진료실 선생님 구인합니다. (주5일제, 야간진료 없음)',
        recruitStartDate: '2024-03-08',
        recruitEndDate: '2024-03-31',
        qualification: 'QLF_CD_002',
        sidoCode: '11',
        sigunguCode: '590',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'Y',
        newYesOrNo: 'N',
        decimalDay: 9,
        topYesOrNo: 'N',
      },
      {
        customerName: '좋은하루치과의원',
        businessmanCustomerCode: '641611',
        hireAnnounceSequenceNumber: 1,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName:
          '[부산동래온천금정] 좋은하루치과에서 함께할 직원분을 모십니다',
        recruitStartDate: '2024-03-07',
        recruitEndDate: '2024-03-31',
        qualification: 'QLF_CD_001|QLF_CD_002',
        sidoCode: '26',
        sigunguCode: '260',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        decimalDay: 9,
        topYesOrNo: 'N',
      },
      {
        customerName: '진플란트치과의원',
        businessmanCustomerCode: '113107',
        hireAnnounceSequenceNumber: 28928,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '진플란트치과의원에서 선생님 모십니다...ㅎ',
        recruitStartDate: '2024-03-04',
        recruitEndDate: '2024-04-04',
        qualification: 'QLF_CD_001',
        sidoCode: '41',
        sigunguCode: '133',
        fileId: '7f1b1bf7-71af-4a61-b1b0-9b125790dfd6',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        decimalDay: 13,
        topYesOrNo: 'N',
      },
      {
        customerName: '어울림치과의원',
        businessmanCustomerCode: '643246',
        hireAnnounceSequenceNumber: 1,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '어울림치과 진료실 선생님 구인합니다',
        recruitStartDate: '2024-02-29',
        recruitEndDate: '2024-03-29',
        qualification: 'QLF_CD_001',
        sidoCode: '11',
        sigunguCode: '650',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        decimalDay: 7,
        topYesOrNo: 'N',
      },
      {
        customerName: '송치과의원',
        businessmanCustomerCode: '984',
        hireAnnounceSequenceNumber: 1,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '5:30 퇴근 송치과에서 간호조무사 선생님 모십니다',
        recruitStartDate: '2024-02-29',
        recruitEndDate: '2024-04-29',
        qualification: 'QLF_CD_002',
        sidoCode: '11',
        sigunguCode: '110',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        decimalDay: 38,
        topYesOrNo: 'N',
      },
      {
        customerName: '매디플란트 치과의원',
        businessmanCustomerCode: '577374',
        hireAnnounceSequenceNumber: 65997,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName:
          '[덕양구 치과] ♥♥경력직 진료실 / 신입 코디네이터 구인합니다. ♥♥',
        recruitStartDate: '2024-02-29',
        recruitEndDate: '2024-04-30',
        qualification: 'QLF_CD_001|QLF_CD_002|QLF_CD_005',
        sidoCode: '41',
        sigunguCode: '281',
        fileId: '8899bd2f-1de9-4c97-9648-570c1530e19a',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        decimalDay: 39,
        topYesOrNo: 'N',
      },
      {
        customerName: '연세수치과',
        businessmanCustomerCode: '600',
        hireAnnounceSequenceNumber: 1,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '실장구인',
        recruitStartDate: '2024-02-27',
        recruitEndDate: '2024-03-27',
        qualification: 'QLF_CD_001|QLF_CD_002|QLF_CD_999',
        sidoCode: '11',
        sigunguCode: '140',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        decimalDay: 5,
        topYesOrNo: 'N',
      },
      {
        customerName: '방배이튼치과의원',
        businessmanCustomerCode: '216911',
        hireAnnounceSequenceNumber: 56878,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName:
          '♥[7호선][2호선]♥ 내방역,방배역 ◈진료실샘◈모십니다. 편안하고 행복한 직장 !',
        recruitStartDate: '2024-02-23',
        recruitEndDate: '2024-03-31',
        qualification: 'QLF_CD_001',
        sidoCode: '11',
        sigunguCode: '650',
        fileId: '5e4fc642-f422-4f63-9d0c-62b5e915f068',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        decimalDay: 9,
        topYesOrNo: 'N',
      },
      {
        customerName: '서울삼정치과의원',
        businessmanCustomerCode: '95875',
        hireAnnounceSequenceNumber: 56940,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '진료실 선생님 모십니다.',
        recruitStartDate: '2024-02-22',
        recruitEndDate: '2024-03-22',
        qualification: 'QLF_CD_001',
        sidoCode: '11',
        sigunguCode: '680',
        fileId: '0632239f-f070-47a9-b0c3-819dd84961a1',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        decimalDay: 0,
        topYesOrNo: 'N',
      },
      {
        customerName: '서울삼정치과의원',
        businessmanCustomerCode: '95875',
        hireAnnounceSequenceNumber: 56939,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '진료실 선생님 모십니다.',
        recruitStartDate: '2024-02-22',
        recruitEndDate: '2024-03-22',
        qualification: 'QLF_CD_002',
        sidoCode: '11',
        sigunguCode: '680',
        fileId: '0632239f-f070-47a9-b0c3-819dd84961a1',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        decimalDay: 0,
        topYesOrNo: 'N',
      },
      {
        customerName: '강임강정서울치과',
        businessmanCustomerCode: '153089',
        hireAnnounceSequenceNumber: 67857,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName:
          '치과 진료실 선생님과 데스크 코디네이터선생님을 구인합니다',
        recruitStartDate: '2024-02-20',
        recruitEndDate: '2024-03-31',
        qualification: 'QLF_CD_001|QLF_CD_005',
        sidoCode: '11',
        sigunguCode: '710',
        fileId: '3ab6e110-510b-4ea3-b678-cebf3584fbf3',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        decimalDay: 9,
        topYesOrNo: 'N',
      },
      {
        customerName: '이백호치과의원',
        businessmanCustomerCode: '66289',
        hireAnnounceSequenceNumber: 61681,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '이백호치과입니다',
        recruitStartDate: '2024-02-20',
        recruitEndDate: '2024-03-31',
        qualification: 'QLF_CD_001',
        sidoCode: '29',
        sigunguCode: '170',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        decimalDay: 9,
        topYesOrNo: 'N',
      },
      {
        customerName: '허인식치과의원',
        businessmanCustomerCode: '148712',
        hireAnnounceSequenceNumber: 68174,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName:
          '잠실새내역 허인식치과 진료실 치과위생사 구인 1명 (신입~5년차)',
        recruitStartDate: '2024-01-30',
        recruitEndDate: '2024-04-30',
        qualification: 'QLF_CD_001',
        sidoCode: '11',
        sigunguCode: '710',
        fileId: 'f3bf751e-e2ce-4333-a12c-226af6f776eb',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        decimalDay: 39,
        topYesOrNo: 'N',
      },
      {
        customerName: '엘에이(LA)치과의원',
        businessmanCustomerCode: '760086',
        hireAnnounceSequenceNumber: 68133,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '협진 하실 치과의사 ,제주시 소재',
        recruitStartDate: '2024-01-22',
        recruitEndDate: '2024-05-31',
        qualification: 'QLF_CD_001|QLF_CD_003|QLF_CD_004',
        sidoCode: '50',
        sigunguCode: '110',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        decimalDay: 70,
        topYesOrNo: 'N',
      },
      {
        customerName: '이튼튼치과의원',
        businessmanCustomerCode: '150723',
        hireAnnounceSequenceNumber: 67994,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName:
          '<김포시 감정동> 이튼튼치과 치과위생사 스텝 채용합니다.',
        recruitStartDate: '2024-01-17',
        recruitEndDate: '2024-03-31',
        qualification: 'QLF_CD_001',
        sidoCode: '41',
        sigunguCode: '570',
        fileId: '078f68fa-37e7-48af-b828-92ef75a79967',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        decimalDay: 9,
        topYesOrNo: 'N',
      },
      {
        customerName: '행복한소아치과의원',
        businessmanCustomerCode: '995077',
        hireAnnounceSequenceNumber: 0,
        hireAnnounceYesOrNo: 'N',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '바른정치과의원 ',
        businessmanCustomerCode: '253253',
        hireAnnounceSequenceNumber: 1,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName:
          '★이전 개원한 홍대 바른정치과에서 진료실 선생님 충원합니다.★',
        recruitStartDate: '2024-03-19',
        recruitEndDate: '2026-03-19',
        qualification: 'QLF_CD_001',
        sidoCode: '11',
        sigunguCode: '440',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '바로나은치과의원',
        businessmanCustomerCode: '572252',
        hireAnnounceSequenceNumber: 65109,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName:
          '★은평구 수색동 신규★ 진료실 팀장 & 스탭 모집합니다. 신입 고년차 환영',
        recruitStartDate: '2024-03-18',
        recruitEndDate: '2026-03-18',
        qualification: 'QLF_CD_001',
        sidoCode: '11',
        sigunguCode: '380',
        fileId: '5d1c8d42-9081-4570-bc77-a2d720acc0ae',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '하얀미소치과',
        businessmanCustomerCode: '9704',
        hireAnnounceSequenceNumber: 1,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '정직원 혹은 파트타임 알바구하고 있습니다. ',
        recruitStartDate: '2024-03-18',
        recruitEndDate: '2026-03-18',
        qualification: 'QLF_CD_001',
        sidoCode: '41',
        sigunguCode: '430',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '김창희치과',
        businessmanCustomerCode: '71572',
        hireAnnounceSequenceNumber: 1,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '대구 달서구 월성동 치과진료실 스텝 구인합니다',
        recruitStartDate: '2024-03-15',
        recruitEndDate: '2026-03-15',
        qualification: 'QLF_CD_001|QLF_CD_002|QLF_CD_003',
        sidoCode: '27',
        sigunguCode: '290',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '노형유디치과',
        businessmanCustomerCode: '235463',
        hireAnnounceSequenceNumber: 67774,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '♥제주도♥ 노형유디치과에서 페이원장님을 모십니다 :)',
        recruitStartDate: '2024-03-14',
        recruitEndDate: '2026-03-14',
        qualification: 'QLF_CD_004',
        sidoCode: '50',
        sigunguCode: '110',
        fileId: '9407ce40-5450-4e32-83dd-6efb1efd6310',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '아름드리치과',
        businessmanCustomerCode: '86718',
        hireAnnounceSequenceNumber: 65108,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '중랑구 먹골역 파트타임 오래 일하실 분 모십니다.',
        recruitStartDate: '2024-03-14',
        recruitEndDate: '2026-03-14',
        qualification: 'QLF_CD_001',
        sidoCode: '11',
        sigunguCode: '260',
        fileId: 'a4787cb6-2b8c-4ef0-8135-5edb11d8e57b',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '서울프라임치과의원',
        businessmanCustomerCode: '147834',
        hireAnnounceSequenceNumber: 1,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName:
          '[진료실 스텝 구인] 1~2년차 치과위생사 선생님! - 주 5일 예정(4월부터)',
        recruitStartDate: '2024-03-13',
        recruitEndDate: '2026-03-13',
        qualification: 'QLF_CD_001',
        sidoCode: '27',
        sigunguCode: '260',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '서울조이치과',
        businessmanCustomerCode: '997728',
        hireAnnounceSequenceNumber: 1,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '서울조이치과 치과위생사 모집',
        recruitStartDate: '2024-05-01',
        recruitEndDate: '2026-05-01',
        qualification: 'QLF_CD_001',
        sidoCode: '28',
        sigunguCode: '185',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '엠플러스치과 ',
        businessmanCustomerCode: '151806',
        hireAnnounceSequenceNumber: 1,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '진료실 스텝 구합니다.',
        recruitStartDate: '2024-03-11',
        recruitEndDate: '2026-03-11',
        qualification: 'QLF_CD_001|QLF_CD_002',
        sidoCode: '11',
        sigunguCode: '215',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '미네소타구강악안면외과치과의원',
        businessmanCustomerCode: '13381',
        hireAnnounceSequenceNumber: 1,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '치위생사, 간호조무사 모집합니다',
        recruitStartDate: '2024-03-11',
        recruitEndDate: '2026-03-11',
        qualification: 'QLF_CD_001',
        sidoCode: '26',
        sigunguCode: '410',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '안양부부치과의원',
        businessmanCustomerCode: '90185',
        hireAnnounceSequenceNumber: 66338,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '진료 스탭 (치위생사/조무사)구합니다. ',
        recruitStartDate: '2024-03-15',
        recruitEndDate: '2026-03-15',
        qualification: 'QLF_CD_001|QLF_CD_002',
        sidoCode: '41',
        sigunguCode: '173',
        fileId: '340fc0c3-d111-4dca-b55f-9a4444c6d763',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '유디구로치과의원',
        businessmanCustomerCode: '306114',
        hireAnnounceSequenceNumber: 1,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName:
          '진료실어시스트 및 스텝 정직원 또는 아르바이트, 주37시간, 야간없음',
        recruitStartDate: '2024-03-08',
        recruitEndDate: '2026-03-08',
        qualification: 'QLF_CD_001|QLF_CD_002',
        sidoCode: '11',
        sigunguCode: '530',
        fileId: 'a2f2d80d-9dd0-4f81-a12d-6c348ad64968',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '휴먼비젼',
        businessmanCustomerCode: '997336',
        hireAnnounceSequenceNumber: 1,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName:
          '연세휴치과&바이스치과 2024년 신입/경력 치과위생사 채용',
        recruitStartDate: '2024-03-08',
        recruitEndDate: '2024-12-31',
        qualification: 'QLF_CD_001',
        fileId: '5c5ebe04-9037-432f-bc87-ef2fa0d24812',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '종로밀레니엄치과의원',
        businessmanCustomerCode: '210949',
        hireAnnounceSequenceNumber: 64684,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName:
          '♥ 종각역 ♥ 신입 & 경력쌤 ☆ 월세지원 / 진료실선생님  충원합니다.',
        recruitStartDate: '2024-03-07',
        recruitEndDate: '2026-03-07',
        qualification: 'QLF_CD_001',
        sidoCode: '11',
        sigunguCode: '110',
        fileId: '9059aee2-631f-4baf-97f4-8e8f0a661381',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '아름다운이치과의원',
        businessmanCustomerCode: '220206',
        hireAnnounceSequenceNumber: 1,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '서초구 아름다운이치과에서 직원을 모집합니다.',
        recruitStartDate: '2024-03-07',
        recruitEndDate: '2026-03-07',
        qualification: 'QLF_CD_002',
        sidoCode: '11',
        sigunguCode: '650',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: 'ABC치과의원',
        businessmanCustomerCode: '235725',
        hireAnnounceSequenceNumber: 1,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '양산 물금 ABC치과에서 진료실 선생님 모집합니다~',
        recruitStartDate: '2024-03-05',
        recruitEndDate: '2026-03-05',
        qualification: 'QLF_CD_001',
        sidoCode: '48',
        sigunguCode: '330',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '다인치과병원',
        businessmanCustomerCode: '151232',
        hireAnnounceSequenceNumber: 2,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '다인치과병원에서 치위생사 선생님을 모집합니다.',
        recruitStartDate: '2024-03-05',
        recruitEndDate: '2026-03-05',
        qualification: 'QLF_CD_001',
        sidoCode: '11',
        sigunguCode: '350',
        fileId: '617e5de7-eeb6-4a71-bc1e-823ff67d99e9',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '곽영태가정의학과의원',
        businessmanCustomerCode: '995254',
        hireAnnounceSequenceNumber: 2,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '치과 개원할 분 찾습니다.',
        recruitStartDate: '2024-03-04',
        recruitEndDate: '2026-03-04',
        qualification: 'QLF_CD_004',
        sidoCode: '48',
        sigunguCode: '170',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '가락연세치과의원',
        businessmanCustomerCode: '44927',
        hireAnnounceSequenceNumber: 2,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '진료실 선생님 모십니다! (주5일)',
        recruitStartDate: '2024-03-04',
        recruitEndDate: '2026-03-04',
        qualification: 'QLF_CD_001',
        sidoCode: '11',
        sigunguCode: '710',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '가지런S치과의원',
        businessmanCustomerCode: '147941',
        hireAnnounceSequenceNumber: 64346,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '[화곡역/기숙사] 2024년 진료팀 신입/경력 공개채용',
        recruitStartDate: '2024-03-02',
        recruitEndDate: '2026-03-02',
        qualification: 'QLF_CD_001|QLF_CD_002',
        sidoCode: '11',
        sigunguCode: '500',
        fileId: 'e4508ffa-2392-4f00-80e4-d30e9d844315',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '아임유치과의원',
        businessmanCustomerCode: '232844',
        hireAnnounceSequenceNumber: 2,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '진료실 치과위생사 모집',
        recruitStartDate: '2024-02-27',
        recruitEndDate: '2026-02-27',
        qualification: 'QLF_CD_001',
        sidoCode: '27',
        sigunguCode: '110',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '마인드치과',
        businessmanCustomerCode: '419420',
        hireAnnounceSequenceNumber: 67758,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '▶[진료실/정규직] 선생님 1년차(신입) 충원합니다◀',
        recruitStartDate: '2024-02-27',
        recruitEndDate: '2026-02-27',
        qualification: 'QLF_CD_001|QLF_CD_002',
        sidoCode: '41',
        sigunguCode: '273',
        fileId: 'c815f696-d2f5-4320-be45-f4a8bb70ad09',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '서울김진철치과 ',
        businessmanCustomerCode: '332271',
        hireAnnounceSequenceNumber: 1,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '주4.5일 상암동 진료실 구인합니다.(최고대우!)',
        recruitStartDate: '2024-02-27',
        recruitEndDate: '2026-02-27',
        qualification: 'QLF_CD_001',
        sidoCode: '11',
        sigunguCode: '440',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '이엘치과병원',
        businessmanCustomerCode: '147975',
        hireAnnounceSequenceNumber: 68095,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '♥이엘치과병원♥에서 보존과 원장님을 모십니다',
        recruitStartDate: '2024-02-24',
        recruitEndDate: '2026-02-24',
        qualification: 'QLF_CD_004',
        sidoCode: '30',
        sigunguCode: '230',
        fileId: '33e32eec-6b3a-4a4e-89bc-cf6a0b6ed9c8',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '이엘치과병원',
        businessmanCustomerCode: '147975',
        hireAnnounceSequenceNumber: 68094,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '​♥이엘치과병원♥에서 예진실 원장님을 모십니다',
        recruitStartDate: '2024-02-24',
        recruitEndDate: '2026-02-24',
        qualification: 'QLF_CD_004',
        sidoCode: '30',
        sigunguCode: '230',
        fileId: '33e32eec-6b3a-4a4e-89bc-cf6a0b6ed9c8',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '박선희치과',
        businessmanCustomerCode: '7507',
        hireAnnounceSequenceNumber: 66303,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName:
          '(동인천역3번출구 앞) 함께 할 치과위생사, 간호조무사, 아르바이트 선생님 모십니다',
        recruitStartDate: '2024-03-18',
        recruitEndDate: '2026-03-18',
        qualification: 'QLF_CD_001',
        sidoCode: '28',
        sigunguCode: '110',
        fileId: '79e47d57-b1f5-453d-806a-e7747cc21332',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '서울부부치과의원',
        businessmanCustomerCode: '213465',
        hireAnnounceSequenceNumber: 54960,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '서울부부치과 채용공고(경기 양평군)',
        recruitStartDate: '2024-02-22',
        recruitEndDate: '2026-02-22',
        qualification: 'QLF_CD_001',
        sidoCode: '41',
        sigunguCode: '830',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '프라임S치과교정과 치과병원',
        businessmanCustomerCode: '432603',
        hireAnnounceSequenceNumber: 2,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName:
          '치위생사 모집 (신입 / 경력 1~4년차 / 파트타임,  교정과 근무)',
        recruitStartDate: '2024-02-20',
        recruitEndDate: '2026-02-20',
        qualification: 'QLF_CD_001',
        sidoCode: '28',
        sigunguCode: '237',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '황선홍치과의원',
        businessmanCustomerCode: '146774',
        hireAnnounceSequenceNumber: 1,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '치위생사,간호조무사,일반인 채용',
        recruitStartDate: '2024-02-19',
        recruitEndDate: '2026-02-19',
        qualification: 'QLF_CD_001|QLF_CD_002',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '유디치과의원',
        businessmanCustomerCode: '294885',
        hireAnnounceSequenceNumber: 1,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '치위생사 ,간호조무사 선생님을 모십니다.',
        recruitStartDate: '2024-02-19',
        recruitEndDate: '2026-02-19',
        qualification: 'QLF_CD_001',
        sidoCode: '30',
        sigunguCode: '170',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '위드치과',
        businessmanCustomerCode: '151800',
        hireAnnounceSequenceNumber: 65220,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '치과토요알바(시간당 2만원)',
        recruitStartDate: '2024-02-19',
        recruitEndDate: '2026-02-19',
        qualification: 'QLF_CD_002',
        sidoCode: '11',
        sigunguCode: '710',
        fileId: '3e027907-423d-44ab-b135-4d948e33bc2d',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '(주)모모앤퍼니',
        businessmanCustomerCode: '252039',
        hireAnnounceSequenceNumber: 63898,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName:
          '★광주시유일의치과병원★기숙사/근속포상/자계비/신입치과위생사환영♥병원급복지!',
        recruitStartDate: '2024-02-16',
        recruitEndDate: '2026-02-16',
        qualification: 'QLF_CD_001',
        sidoCode: '41',
        sigunguCode: '610',
        fileId: 'c45f5bad-2d02-4195-8e3e-48a69f68e547',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '월드치과의원',
        businessmanCustomerCode: '5134',
        hireAnnounceSequenceNumber: 68035,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '치과위생사 및 간호조무사 모집',
        recruitStartDate: '2024-02-16',
        recruitEndDate: '2026-02-16',
        qualification: 'QLF_CD_001',
        sidoCode: '11',
        sigunguCode: '530',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
      {
        customerName: '오희영치과 ',
        businessmanCustomerCode: '306277',
        hireAnnounceSequenceNumber: 3,
        hireAnnounceStatCode: 'HIRE_ANUN_STACD_100',
        hireAnnounceName: '포항치과 오희영치과 진료실 경력직 치과위생사 구인',
        recruitStartDate: '2024-02-15',
        recruitEndDate: '9999-12-31',
        qualification: 'QLF_CD_001',
        hireAnnounceYesOrNo: 'Y',
        readYesOrNo: 'N',
        newYesOrNo: 'N',
        topYesOrNo: 'N',
      },
    ],
  },
  setState(newState) {
    this.state = { ...this.state, ...newState };
  },
};

module.exports = store;
